version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8001
    networks:
      - kontour-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./backend/kontour_data:/app/kontour_data
      - ./backend/quantum_kontour_data:/app/quantum_kontour_data
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
      - CORS_ORIGINS=http://localhost:3000,https://kontourcoin.io
    networks:
      - kontour-network

networks:
  kontour-network:
    driver: bridge